version: '3.1'
services:
  stats-server:
    build: ./stats-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - STATS_POSTGRES_USER=stats-root
      - STATS_POSTGRES_PASSWORD=stats-root
      - STATS_SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats-root
      - POSTGRES_PASSWORD=stats-root

  ewm-service:
    build: ./ewm-service
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EWM_SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - EWM_POSTGRES_USER=ewm-root
      - EWM_POSTGRES_PASSWORD=ewm-root
      - EWM_SERVER_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm-root
      - POSTGRES_PASSWORD=ewm-root