create table if not exists endpoint_hits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(255) NOT NULL,
  ip VARCHAR(16) NOT NULL,
  time_stamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);